# Generated by Django 6.0.1 on 2026-01-17 04:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Kenyan', max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('customer_type', models.CharField(choices=[('student', 'Student'), ('tenant', 'Tenant'), ('patient', 'Patient'), ('member', 'Member'), ('subscriber', 'Subscriber'), ('other', 'Other')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=17)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('employer_address', models.TextField(blank=True)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('receive_sms', models.BooleanField(default=True)),
                ('receive_email', models.BooleanField(default=True)),
                ('receive_whatsapp', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('class', 'Class/Grade'), ('building', 'Building/Block'), ('ward', 'Ward/Department'), ('plan', 'Subscription Plan'), ('custom', 'Custom Group')], default='custom', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('default_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customers', models.ManyToManyField(blank=True, related_name='groups', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_groups', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'status'], name='customers_c_organiz_628fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_code'], name='customers_c_custome_116ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_payment_date'], name='customers_c_last_pa_2c1cfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('organization', 'phone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='customergroup',
            unique_together={('organization', 'name')},
        ),
    ]
